# 项目相关配置
FastGo:
  # 名称
  name: FastGo
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2020

spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  #文件上传设置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8